#!/usr/bin/env bash

get_volume() {
  pactl get-sink-volume @DEFAULT_SINK@ | grep -oP '\d+%' | head -1 | tr -d '%'
}

get_mute() {
  pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}' | grep -q yes && echo 1 || echo 0
}

case "$1" in
  "volume")
    get_volume
    pactl subscribe \
      | grep --line-buffered "Event 'change' on sink " \
      | while read -r _; do
          get_volume
        done
    ;;
  "mute")
    get_mute
    pactl subscribe \
      | grep --line-buffered "Event 'change' on sink " \
      | while read -r _; do
          get_mute
        done
    ;;
esac

